const labels = {
  it: {
    skiplinksNav: "Menù skiplinks",
    skipLinkMain: "Vai al contenuto principale",
    skipLinkFooter: "Vai al footer",
    send: `Invia richiesta`,
    sending: `Invio richiesta in corso ...`,
    email: `Email`,
    company: `Azienda`,
    firstName: `Nome`,
    lastName: `Cognome`,
    volume: `Volumi per anno`,
    message: `Messaggio`,
    privacy: `Accetto il trattamento dei dati personali ai sensi della`,
    requiredField: `Questo campo è obbligatorio`,
    invalidField: `Inserire un valore valido per questo campo`,
    response200: `Grazie per averci contattato, abbiamo registrato la tua richiesta di contatto`,
    error: `Si è verificatao un problema durante l'invio della richiesta`,
    response422: `Grazie per averci contattato, abbiamo già in archivio la tua richiesta di contatto`,
    reset: `Invia nuova richiesta`,
    iubenda_policy_id: `43171605`,
    acceptPrivacy: `Devi accettare la nostra politica sulla privacy per continuare`,
  },
  en: {
    skiplinksNav: "Skiplinks",
    skipLinkMain: "Skip to main content",
    skipLinkFooter: "Jump to footer",
    send: `Send Request`,
    sending: `Sending ...`,
    email: `Email`,
    company: `Company`,
    firstName: `First Name`,
    lastName: `Last Name`,
    message: `Message`,
    privacy: `I accept the processing of personal data pursuant to the`,
    volume: `Yearly volumes`,
    requiredField: `This field is required`,
    invalidField: `Insert a valid value for this field`,
    response200: `Thank You fot contacting Us, We have recorded your contact's request`,
    error: `An unexpected error occurred, please rety later`,
    response422: `Thank You fot contacting Us, We have already recorded your contact's request`,
    reset: `Send another request`,
    iubenda_policy_id: `43171605`,
    acceptPrivacy: `You must agree to our privacy policy to continue`,
  },
  pl: {
    skiplinksNav: "Skiplinki",
    skipLinkMain: "Przejdź do głównej treści",
    skipLinkFooter: "Przejdź do stopki",
    send: `Wyślij formularz`,
    sending: `Wysyłanie ...`,
    email: `Adres E-mail`,
    company: `Firma`,
    firstName: `Imię`,
    lastName: `Nazwisko`,
    message: `Tutaj wpisz Twoją wiadomość`,
    privacy: `Wyrażam zgodę na przetwarzanie danych osobowych na podstawie`,
    volume: `Wielkości Roczne`,
    requiredField: `o pole jest obowiązkowe`,
    invalidField: `Wprowadź prawidłową wartość dla tego pola`,
    response200: `Dziękujemy za kontakt z nami, zarejestrowaliśmy Twoje zgłoszenie`,
    error: `Podczas wysyłania żądania wystąpił problem`,
    response422: `Dziękujemy za kontakt, mamy już Twoją prośbę w aktach.`,
    reset: `Wyślij nowy wniosek`,
    iubenda_policy_id: `43171605`,
    acceptPrivacy: `Aby kontynuować, musisz zaakceptować naszą politykę prywatności`,
  },
};
1;
function getLabel(locale = 'it', lbl = '') {
  return labels[locale.toLowerCase()][lbl] || lbl;
}

export default getLabel;
